name: covid_19
description: covid-19 application

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.2.0
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  toast: ^0.1.5
  foldable_sidebar: ^1.0.0
  qr_flutter: ^3.1.0
  url_launcher: ^5.5.1
  tweet_webview: ^0.2.2
  fl_chart: ^0.11.0
  http: ^0.12.2
  shared_preferences: ^0.5.10


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: JockeyOne
      fonts:
        - asset: fonts/JockeyOne-Regular.ttf
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-ExtraLight.ttf
        - asset: fonts/RobotoSlab-SemiBold.ttf
